name: e2e-latest-rancher
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 22 * * *
permissions: read-all
jobs:
  e2e-tests:
    uses: ./.github/workflows/e2e.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
